"""NCTForge — transport-neutral BNCT research verification workbench.

Research software only: not a medical device, not commissioned for any
facility, and not a dose calculator. All validation, geometry, contract, and
evidence behavior below is executed by the authoritative Rust implementation;
this package adds no scientific logic of its own.

Transport actions remain unavailable until the Rust capability and evidence
gates pass; :func:`backends` reports those flags honestly.
"""

from nctforge._nctforge import (
    AppliedDoseStatistic,
    AppliedFractionation,
    Artifact,
    Backend,
    BiologicalDoseBundle,
    BiologicalModel,
    CaseManifest,
    CaseVerification,
    ComponentProfile,
    DoseVolume,
    DoseVolumeHistogram,
    EndpointEvaluation,
    EndpointModel,
    Exposure,
    ExposurePlan,
    FixedSource,
    GeneratedCase,
    Geometry,
    Material,
    NctForgeError,
    PhysicalDoseBundle,
    RegionDoseMetrics,
    ResponseGenerationMethod,
    ResponseSet,
    Structure,
    VerifiedCase,
    accumulate_exposures,
    apply_model,
    backends,
    collect_run,
    combine_utcp,
    compute_dvh,
    compute_dvh_biological,
    compute_metrics,
    compute_metrics_biological,
    evaluate_endpoint,
    evaluate_endpoint_biological,
    export_mcnp_deck,
    exposure_plan_diagnostics,
    file_sha256,
    generate_case,
    import_component_dose,
    import_mcnp_meshtal,
    import_phits,
    load_biological_model,
    load_case,
    load_component_profile,
    load_endpoint_evaluation,
    load_endpoint_model,
    load_exposure_plan,
    load_fixed_source,
    load_material,
    load_physical_dose_bundle,
    load_response_generation_method,
    load_response_set,
    plan_table_read,
    plan_table_write,
    read_manifest,
    verify_case,
    verify_evidence_bundle,
)
from nctforge._nctforge import __version__ as _extension_version

__version__ = _extension_version

__all__ = [
    "AppliedDoseStatistic",
    "AppliedFractionation",
    "Artifact",
    "Backend",
    "BiologicalDoseBundle",
    "BiologicalModel",
    "CaseManifest",
    "CaseVerification",
    "ComponentProfile",
    "DoseVolume",
    "DoseVolumeHistogram",
    "EndpointEvaluation",
    "EndpointModel",
    "Exposure",
    "ExposurePlan",
    "FixedSource",
    "GeneratedCase",
    "Geometry",
    "Material",
    "NctForgeError",
    "PhysicalDoseBundle",
    "RegionDoseMetrics",
    "ResponseGenerationMethod",
    "ResponseSet",
    "Structure",
    "VerifiedCase",
    "__version__",
    "accumulate_exposures",
    "apply_model",
    "backends",
    "collect_run",
    "combine_utcp",
    "compute_dvh",
    "compute_dvh_biological",
    "compute_metrics",
    "compute_metrics_biological",
    "evaluate_endpoint",
    "evaluate_endpoint_biological",
    "export_mcnp_deck",
    "exposure_plan_diagnostics",
    "file_sha256",
    "generate_case",
    "import_component_dose",
    "import_mcnp_meshtal",
    "import_phits",
    "load_biological_model",
    "load_case",
    "load_component_profile",
    "load_endpoint_evaluation",
    "load_endpoint_model",
    "load_exposure_plan",
    "load_fixed_source",
    "load_material",
    "load_physical_dose_bundle",
    "load_response_generation_method",
    "load_response_set",
    "plan_table_read",
    "plan_table_write",
    "read_manifest",
    "verify_case",
    "verify_evidence_bundle",
]
